###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://www.project-piper.io/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  BuildTool: "mta"

### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Test:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "94793145-fa9c-4168-a26a-133e62cc8f36"
    cfSpace: "DEVSpace"
    cfAppName: "tmsproject"
    cfCredentialsId: "deploy-to-cf"
    iuVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "94793145-fa9c-4168-a26a-133e62cc8f36"
    cfSpace: "DEVSpace"
    cfAppName: "tmsproject"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  
  tmsUpload:
    nodeName: "qa"
    credentialsID: "cred.dev"
