### General project setup
general:
  buildTool: "mta"

### Stage-specific configuration
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "94793145-fa9c-4168-a26a-133e62cc8f36"
    cfSpace: "DEVSpace"
    cfAppName: "tmsproject"
    cfCredentialsId: "deploy-to-cf"
    iuVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "94793145-fa9c-4168-a26a-133e62cc8f36"
    cfSpace: "DEVSpace"
    cfAppName: "tmsproject"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "qa"
    credentialsId: "cred.dev"
